<?php

namespace App\Http\Controllers\userManagement;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use App\Models\User;
use App\Models\Role;
use App\Models\Department;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::with(['role', 'department'])->get();
        return view('modules.User-management.index', compact('users'));
    }

    public function profile()
    {
        $user = Auth::user();
        $user->load(['department', 'role']);
        
        $joinDate = $user->created_at ?? now();
        $yearsOfService = $joinDate->diffInYears(now());
        $monthsOfService = $joinDate->diffInMonths(now()) % 12;
        
        $leaveBalance = $this->calculateLeaveBalance($user);
        $performance = $this->getPerformanceRating($user);
        $completedProjects = $this->getCompletedProjectsCount($user);

        return view('modules.User-management.profile', compact(
            'user', 
            'yearsOfService', 
            'monthsOfService',
            'leaveBalance',
            'performance',
            'completedProjects'
        ));
    }

    // department users
    public function departments()
    {
        return view('modules.User-management.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $roles = Role::all();
        $departments = Department::all();
        $supervisors = User::whereIn('role_id', function($query) {
            $query->select('id')->from('roles')->whereIn('name', ['department_head', 'supervisor', 'manager']);
        })->get();

        return view('modules.User-management.create', compact('roles', 'departments', 'supervisors'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|email|unique:users',
            'phone' => 'nullable|string|max:20',
            'date_of_birth' => 'nullable|date',
            'gender' => 'nullable|in:male,female,other',
            'address' => 'nullable|string|max:500',
            'emergency_contact' => 'nullable|string|max:20',
            'profile_picture' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
            
            // Employment Information
            'role_id' => 'required|exists:roles,id',
            'department_id' => 'nullable|exists:departments,id',
            'position' => 'required|string|max:255',
            'employment_type' => 'required|in:full_time,part_time,contract,intern',
            'join_date' => 'required|date',
            'supervisor_id' => 'nullable|exists:users,id',
            
            // Account Settings
            'password' => 'required|string|min:8|confirmed',
            'status' => 'required|in:active,inactive,suspended',
        ]);

        try {
            $userData = [
                'first_name' => $validated['first_name'],
                'last_name' => $validated['last_name'],
                'email' => $validated['email'],
                'password' => Hash::make($validated['password']),
                'role_id' => $validated['role_id'],
                'department_id' => $validated['department_id'],
                'phone' => $validated['phone'],
                'date_of_birth' => $validated['date_of_birth'],
                'gender' => $validated['gender'],
                'address' => $validated['address'],
                'emergency_contact' => $validated['emergency_contact'],
                'employment_type' => $validated['employment_type'],
                'join_date' => $validated['join_date'],
                'supervisor_id' => $validated['supervisor_id'],
                'status' => $validated['status'],
            ];

            // Handle profile picture upload
            if ($request->hasFile('profile_picture')) {
                $profilePicture = $request->file('profile_picture');
                
                // Generate unique filename
                $filename = time() . '_' . uniqid() . '.' . $profilePicture->getClientOriginalExtension();
                
                // Store in profile_pictures directory
                $path = $profilePicture->storeAs('profile_pictures', $filename, 'public');
                $userData['profile_picture'] = $path;
            }

            // Create the user - employee_id will be auto-generated by the model boot method
            $user = User::create($userData);

            return redirect()->route('users.index')->with('success', 'User created successfully! Employee ID: ' . $user->employee_id);

        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Error creating user: ' . $e->getMessage())->withInput();
        }
    }

    /**
     * Show the change password form
     */
    public function showChangePasswordForm()
    {
        return view('modules.user-management.change-password');
    }

    /**
     * Handle password change request
     */
    public function changePassword(Request $request)
    {
        $request->validate([
            'current_password' => 'required',
            'new_password' => 'required|min:8|confirmed',
        ]);

        $user = Auth::user();

        // Check if current password matches
        if (!Hash::check($request->current_password, $user->password)) {
            return back()->withErrors(['current_password' => 'Current password is incorrect']);
        }

        // Update password
        $user->password = Hash::make($request->new_password);
        $user->save();

        return redirect()->route('users.profile')->with('success', 'Password changed successfully!');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the user profile.
     */
    public function editProfile()
    {
        $user = Auth::user();
        $user->load(['department', 'role', 'supervisor']);
        
        return view('modules.User-management.edit', compact('user'));
    }

    /**
     * Update the user's profile.
     */
    public function updateProfile(Request $request)
    {
        $user = Auth::user();

        $validated = $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email,' . $user->id,
            'phone' => 'nullable|string|max:20',
            'date_of_birth' => 'nullable|date',
            'gender' => 'nullable|in:male,female,other',
            'address' => 'nullable|string|max:500',
            'emergency_contact' => 'nullable|string|max:20',
            'profile_picture' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);

        try {
            $userData = [
                'first_name' => $validated['first_name'],
                'last_name' => $validated['last_name'],
                'email' => $validated['email'],
                'phone' => $validated['phone'],
                'date_of_birth' => $validated['date_of_birth'],
                'gender' => $validated['gender'],
                'address' => $validated['address'],
                'emergency_contact' => $validated['emergency_contact'],
            ];

            // Handle profile picture upload
            if ($request->hasFile('profile_picture')) {
                // Delete old profile picture if exists
                if ($user->profile_picture && Storage::disk('public')->exists($user->profile_picture)) {
                    Storage::disk('public')->delete($user->profile_picture);
                }
                
                $profilePicture = $request->file('profile_picture');
                
                // Generate unique filename
                $filename = time() . '_' . uniqid() . '.' . $profilePicture->getClientOriginalExtension();
                
                // Store in profile_pictures directory
                $path = $profilePicture->storeAs('profile_pictures', $filename, 'public');
                $userData['profile_picture'] = $path;
            }

            // Handle profile picture removal
            if ($request->has('remove_profile_picture')) {
                if ($user->profile_picture && Storage::disk('public')->exists($user->profile_picture)) {
                    Storage::disk('public')->delete($user->profile_picture);
                }
                $userData['profile_picture'] = null;
            }

            $user->update($userData);

            return redirect()->route('users.profile')->with('success', 'Profile updated successfully!');

        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Error updating profile: ' . $e->getMessage())->withInput();
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }

    /**
     * Calculate leave balance for user
     */
    private function calculateLeaveBalance($user)
    {
        // Implement your leave balance calculation logic here
        return 18; // Default value
    }

    /**
     * Get performance rating for user
     */
    private function getPerformanceRating($user)
    {
        // Implement your performance rating logic here
        return 'Excellent';
    }

    /**
     * Get completed projects count for user
     */
    private function getCompletedProjectsCount($user)
    {
        // Implement your projects logic here
        return 12;
    }
}